# Generated by Django 3.1 on 2020-08-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
    ]
