# Generated by Django 3.1 on 2020-08-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_auto_20200829_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='review_tutor', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
