version: "3.7"

services:
  sessions:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - sessions-db
  sessions-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sessions
      - POSTGRES_PASSWORD=sessions
      - POSTGRES_DB=sessions_dev

volumes:
  postgres_data:
