# Generated by Django 3.1 on 2020-08-27 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200827_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grad_year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1990)]),
        ),
    ]
