# Generated by Django 3.1 on 2020-08-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_college'),
        ('users', '0003_auto_20200827_1214'),
    ]

    operations = [
    ]
